/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Form13F {
  schemaVersion?: string
  headerData: HeaderData
  formData: FormData
}
export interface HeaderData {
  submissionType: string
  filerInfo: FilerInfo
}
export interface FilerInfo {
  liveTestFlag: string
  flags?: Flags
  filer: Filer
  contact?: Contact
  notifications?: Notifications
  periodOfReport: string
}
export interface Flags {
  confirmingCopyFlag?: boolean
  returnCopyFlag?: boolean
  overrideInternetFlag?: boolean
}
export interface Filer {
  credentials: Credentials
  fileNumber?: string
}
export interface Credentials {
  cik: string
  ccc: string
}
export interface Contact {
  name?: string
  phoneNumber?: string
  emailAddress?: string
}
export interface Notifications {
  emailAddress?: string
}
export interface FormData {
  coverPage: CoverPage
  signatureBlock: SignatureBlock
  summaryPage?: SummaryPage
  documents: Array<OtherDocument>
}
export interface CoverPage {
  reportCalendarOrQuarter: string
  isAmendment?: boolean
  amendmentNumber?: number
  amendmentInfo?: AmendmentInfo
  filingManager: FilingManager
  reportType: string
  form13FFileNumber?: string
  otherManagerInfo?: OtherManagerInfo
  provideInfoForInstruction5: boolean
  additionalInformation?: string
}
export interface AmendmentInfo {
  amendmentType?: string
  confDeniedExpired?: boolean
  dataDeniedExpired?: string
  dateReported?: string
  reasonForNonConfidentiality?: string
}
export interface FilingManager {
  name: string
  address: Address
}
export interface Address {
  street1: string
  street2?: string
  city: string
  stateOrCountry: string
  zipCode: string
}
export interface OtherManagerInfo {
  otherManager?: OtherManager
}
export interface OtherManager {
  cik?: string
  name?: string
  form13FFileNumber?: string
}
export interface SignatureBlock {
  name: string
  title: string
  phone: string
  signature: string
  city: string
  stateOrCountry: string
  signatureDate: string
}
export interface SummaryPage {
  otherIncludedManagersCount: number
  tableEntryTotal: number
  tableValueTotal: number
  isConfidentialOmitted?: boolean
  otherManagers: Array<OtherManagerWithSequence>
}
export interface OtherManagerWithSequence {
  sequenceNumber?: number
  manager?: OtherManager
}
export interface OtherDocument {
  conformedName?: string
  conformedDocumentType?: string
  description?: string
  contents?: string
}
export interface Form13FTable {
  entries: Array<TableEntry>
}
export interface TableEntry {
  nameOfIssuer: string
  titleOfClass: string
  cusip: string
  figi?: string
  value: number
  sharesOrPrintAmount: SharesOrPrintAmount
  putCall?: string
  investmentDiscretion: string
  otherManager: Array<number>
  votingAuthority: VotingAuthority
}
export interface SharesOrPrintAmount {
  amount: number
  sharesOrPrintType: string
}
export interface VotingAuthority {
  sole: number
  shared: number
  none: number
}
export function parseForm13F(form: string): Form13F
export function parseForm13FTable(table: string): Form13FTable
export interface Xbrl {
  facts: Array<Fact>
}
export interface Fact {
  context: Context
  concept: string
  value: unknown
  decimals?: string
  unit?: string
}
export interface Context {
  entity: string
  segments: Array<Segment>
  period: Period
}
export interface Segment {
  dimension: string
  member: string
}
export interface Period {
  instant?: string
  startDate?: string
  endDate?: string
}
export function parseXbrl(xbrl: string): Xbrl
